spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: app
          uri: http://localhost:8080/
          predicates:
            - Path=/api/products/**
        - id: CalculatorMicroservice
          uri: http://localhost:8081/
          predicates:
            - Path=/api/mwst/**